// Static require map for all 34 installation guide pages.
// Metro bundler requires static paths — dynamic requires are not supported.
const DiagramImages: Record<string, number> = {
  'page-01': require('@/assets/diagrams/page-01.png'),
  'page-02': require('@/assets/diagrams/page-02.png'),
  'page-03': require('@/assets/diagrams/page-03.png'),
  'page-04': require('@/assets/diagrams/page-04.png'),
  'page-05': require('@/assets/diagrams/page-05.png'),
  'page-06': require('@/assets/diagrams/page-06.png'),
  'page-07': require('@/assets/diagrams/page-07.png'),
  'page-08': require('@/assets/diagrams/page-08.png'),
  'page-09': require('@/assets/diagrams/page-09.png'),
  'page-10': require('@/assets/diagrams/page-10.png'),
  'page-11': require('@/assets/diagrams/page-11.png'),
  'page-12': require('@/assets/diagrams/page-12.png'),
  'page-13': require('@/assets/diagrams/page-13.png'),
  'page-14': require('@/assets/diagrams/page-14.png'),
  'page-15': require('@/assets/diagrams/page-15.png'),
  'page-16': require('@/assets/diagrams/page-16.png'),
  'page-17': require('@/assets/diagrams/page-17.png'),
  'page-18': require('@/assets/diagrams/page-18.png'),
  'page-19': require('@/assets/diagrams/page-19.png'),
  'page-20': require('@/assets/diagrams/page-20.png'),
  'page-21': require('@/assets/diagrams/page-21.png'),
  'page-22': require('@/assets/diagrams/page-22.png'),
  'page-23': require('@/assets/diagrams/page-23.png'),
  'page-24': require('@/assets/diagrams/page-24.png'),
  'page-25': require('@/assets/diagrams/page-25.png'),
  'page-26': require('@/assets/diagrams/page-26.png'),
  'page-27': require('@/assets/diagrams/page-27.png'),
  'page-28': require('@/assets/diagrams/page-28.png'),
  'page-29': require('@/assets/diagrams/page-29.png'),
  'page-30': require('@/assets/diagrams/page-30.png'),
  'page-31': require('@/assets/diagrams/page-31.png'),
  'page-32': require('@/assets/diagrams/page-32.png'),
  'page-33': require('@/assets/diagrams/page-33.png'),
  'page-34': require('@/assets/diagrams/page-34.png'),
};

export default DiagramImages;
